from __future__ import annotations

import argparse
import asyncio
import json
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from .dashboard import Dashboard
from .mcp_proxy import run_mcp_proxy
from .models import DecisionKind, ToolCall, Usage
from .policy import Policy, PolicyConfigError

EXIT_BY_DECISION = {
    DecisionKind.ALLOW: 0,
    DecisionKind.REQUIRE_APPROVAL: 3,
    DecisionKind.BLOCK: 4,
}

STARTER_POLICY: dict[str, Any] = {
    "_comment": (
        "Starter policy generated by agent-firewall init. Rules are evaluated "
        "top to bottom and the default decision is intentionally block."
    ),
    "default_decision": "block",
    "audit_arguments": "hash",
    "budget": {
        "_comment": "Conservative run budgets; tune these to your workflow.",
        "max_calls": 100,
        "max_calls_per_tool": 25,
        "max_identical_calls": 3,
        "max_cost_usd": "1.00",
    },
    "rules": [
        {
            "_comment": "Read-only discovery tools are usually safe to allow.",
            "tool": "list*",
            "decision": "allow",
            "reason": "read-only listing",
        },
        {
            "tool": "read*",
            "decision": "allow",
            "reason": "read-only access",
        },
        {
            "tool": "get*",
            "decision": "allow",
            "reason": "read-only lookup",
        },
        {
            "tool": "search*",
            "decision": "allow",
            "reason": "read-only search",
        },
        {
            "tool": "fetch",
            "decision": "allow",
            "reason": "read-only fetch",
        },
        {
            "_comment": "Destructive or external side-effect verbs need a human.",
            "tool": "*delete*",
            "decision": "require_approval",
            "reason": "destructive delete requires approval",
        },
        {
            "tool": "*remove*",
            "decision": "require_approval",
            "reason": "destructive remove requires approval",
        },
        {
            "tool": "*write*",
            "decision": "require_approval",
            "reason": "write operation requires approval",
        },
        {
            "tool": "*create*",
            "decision": "require_approval",
            "reason": "create operation requires approval",
        },
        {
            "tool": "*update*",
            "decision": "require_approval",
            "reason": "update operation requires approval",
        },
        {
            "tool": "*send*",
            "decision": "require_approval",
            "reason": "external send requires approval",
        },
        {
            "tool": "*execute*",
            "decision": "require_approval",
            "reason": "command execution requires approval",
        },
        {
            "tool": "*run*",
            "decision": "require_approval",
            "reason": "command execution requires approval",
        },
        {
            "tool": "*shell*",
            "decision": "require_approval",
            "reason": "shell access requires approval",
        },
    ],
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="agent-firewall",
        description="Evaluate AI-agent tool calls before they execute.",
    )
    commands = parser.add_subparsers(dest="command", required=True)

    init = commands.add_parser(
        "init",
        help="write a starter policy and print an MCP config snippet",
    )
    init.add_argument("--policy", type=Path, default=Path("policy.json"))
    init.add_argument("--audit", type=Path, default=Path("firewall-audit.jsonl"))
    init.add_argument("--state", type=Path, default=Path("firewall.db"))
    init.add_argument("--server-name", default="protected-server")
    init.add_argument("--force", action="store_true")
    init.add_argument("server_command", nargs=argparse.REMAINDER)

    check = commands.add_parser("check", help="evaluate one proposed tool call")
    check.add_argument("--policy", type=Path, required=True)
    check.add_argument("--tool", required=True)
    check.add_argument("--arguments", default="{}", help="tool arguments as JSON")
    check.add_argument("--cost", default="0", help="estimated cost in USD")

    replay = commands.add_parser(
        "replay",
        help="replay complaint-derived scenarios against a policy",
    )
    replay.add_argument("--policy", type=Path, required=True)
    replay.add_argument("--scenarios", type=Path, required=True)

    mcp = commands.add_parser("mcp", help="guard a local MCP stdio server")
    mcp.add_argument("--policy", type=Path, required=True)
    mcp.add_argument("--audit", type=Path)
    mcp.add_argument("--state", type=Path)
    approval = mcp.add_mutually_exclusive_group()
    approval.add_argument(
        "--approve-terminal",
        action="store_true",
        help="prompt on the controlling terminal for approval-gated calls",
    )
    approval.add_argument(
        "--approve-web",
        action="store_true",
        help="wait for decisions from the localhost dashboard",
    )
    mcp.add_argument("--approval-timeout", type=float, default=300)
    mcp.add_argument("server_command", nargs=argparse.REMAINDER)

    dashboard = commands.add_parser(
        "dashboard",
        help="run the local audit and approval dashboard",
    )
    dashboard.add_argument("--policy", type=Path, required=True)
    dashboard.add_argument("--audit", type=Path, required=True)
    dashboard.add_argument("--state", type=Path, required=True)
    dashboard.add_argument("--host", default="127.0.0.1")
    dashboard.add_argument("--port", type=int, default=8787)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.command == "init":
            return _init(args)
        if args.command == "check":
            return _check(args)
        if args.command == "dashboard":
            return _dashboard(args)
        if args.command == "mcp":
            return asyncio.run(
                run_mcp_proxy(
                    args.policy,
                    args.server_command,
                    audit_path=args.audit,
                    state_path=args.state,
                    approve_terminal=args.approve_terminal,
                    approve_web=args.approve_web,
                    approval_timeout=args.approval_timeout,
                )
            )
        return _replay(args)
    except (OSError, PolicyConfigError, ValueError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


def _init(args: argparse.Namespace) -> int:
    policy_path = args.policy.expanduser()
    if policy_path.exists() and not args.force:
        raise ValueError(f"{policy_path} already exists; pass --force to overwrite")
    policy_path.parent.mkdir(parents=True, exist_ok=True)
    policy_path.write_text(
        json.dumps(STARTER_POLICY, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )

    command = _server_command_or_placeholder(args.server_command)
    config = _mcp_config(
        args.server_name,
        policy_path.resolve(),
        args.audit.expanduser().resolve(),
        args.state.expanduser().resolve(),
        command,
    )
    print(f"Wrote {policy_path.resolve()}")
    print()
    print("MCP config snippet:")
    print(json.dumps(config, indent=2))
    return 0


def _check(args: argparse.Namespace) -> int:
    arguments = json.loads(args.arguments)
    if not isinstance(arguments, dict):
        raise ValueError("--arguments must decode to a JSON object")

    policy = Policy.load(args.policy)
    call = ToolCall.create(args.tool, arguments, args.cost)
    decision = policy.evaluate(call, Usage())
    print(json.dumps(decision.as_dict(), sort_keys=True))
    return EXIT_BY_DECISION[decision.kind]


def _replay(args: argparse.Namespace) -> int:
    policy = Policy.load(args.policy)
    scenarios = json.loads(args.scenarios.read_text(encoding="utf-8"))
    if not isinstance(scenarios, list):
        raise ValueError("scenario file must contain a JSON list")

    failures = 0
    for scenario in scenarios:
        result = _run_scenario(policy, scenario)
        failures += int(not result["passed"])
        print(json.dumps(result, sort_keys=True))

    summary = {
        "passed": len(scenarios) - failures,
        "failed": failures,
        "total": len(scenarios),
    }
    print(json.dumps({"summary": summary}, sort_keys=True))
    return 1 if failures else 0


def _dashboard(args: argparse.Namespace) -> int:
    dashboard = Dashboard(
        args.policy,
        args.audit,
        args.state,
        host=args.host,
        port=args.port,
    )
    try:
        dashboard.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        dashboard.server.server_close()
    return 0


def _server_command_or_placeholder(command: Sequence[str]) -> list[str]:
    if command and command[0] == "--":
        command = command[1:]
    if command:
        return list(command)
    return ["python", "/absolute/path/to/your_mcp_server.py"]


def _mcp_config(
    server_name: str,
    policy_path: Path,
    audit_path: Path,
    state_path: Path,
    server_command: Sequence[str],
) -> dict[str, Any]:
    return {
        "mcpServers": {
            server_name: {
                "command": "agent-firewall",
                "args": [
                    "mcp",
                    "--policy",
                    str(policy_path),
                    "--audit",
                    str(audit_path),
                    "--state",
                    str(state_path),
                    "--approve-terminal",
                    "--",
                    *server_command,
                ],
            }
        }
    }


def _run_scenario(policy: Policy, scenario: Any) -> dict[str, Any]:
    if not isinstance(scenario, dict):
        raise ValueError("each scenario must be a JSON object")
    scenario_id = scenario.get("id")
    calls = scenario.get("calls")
    expected = scenario.get("expected_decisions")
    if not isinstance(scenario_id, str) or not scenario_id:
        raise ValueError("scenario id must be a non-empty string")
    if not isinstance(calls, list) or not isinstance(expected, list):
        raise ValueError(f"{scenario_id}: calls and expected_decisions must be lists")
    if len(calls) != len(expected):
        raise ValueError(f"{scenario_id}: each call needs an expected decision")

    usage = Usage()
    actual: list[str] = []
    for index, raw_call in enumerate(calls):
        if not isinstance(raw_call, dict):
            raise ValueError(f"{scenario_id}: calls[{index}] must be an object")
        try:
            call = ToolCall.create(
                raw_call.get("tool"),
                raw_call.get("arguments"),
                raw_call.get("estimated_cost_usd", 0),
            )
        except ValueError as exc:
            raise ValueError(f"{scenario_id}: calls[{index}]: {exc}") from exc
        decision = policy.evaluate(call, usage)
        actual.append(decision.kind.value)
        if decision.kind is DecisionKind.ALLOW:
            usage.record(call)

    return {
        "id": scenario_id,
        "source_url": scenario.get("source_url"),
        "expected": expected,
        "actual": actual,
        "passed": actual == expected,
    }


if __name__ == "__main__":
    raise SystemExit(main())
